name: PR notifications

on:
  pull_request_target:
    branches:
      - main
      - stable/[0-9]+\.[0-9]+
    types:
      - opened

jobs:
  pr-notifications:
    name: Send PR notifications
    runs-on: ubuntu-latest
    steps:
      - name: Send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_NOTIFICATIONS_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          disable_web_page_preview: true
          format: markdown
          message: |
            New PR in *${{ github.repository }}*: `${{ github.event.pull_request.title }}`
            ${{ github.server_url }}/${{ github.repository }}/pull/${{ github.event.number }}

